### PR TITLE
Chapter Branch

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
basically this allows the app to differentiate between multiple chapter lists/types. e.g, multiple different languages or volume/chapter release or coloured/non-coloured version etc.

App will show a drop down above chapter list and allow user to select the branch they want. Only one branch can be enabled at a time. 
This would allow merging language based factory sources into one, which provides all language chapters in a single entry, separated by the branch.

~totally not stolen idea from kotatsu~

Another approach can be to make `val chapters: List<Pair<String, List<Chapter>>>` in the `Manga` model, but that seems dirty...

### CODE REVIEW

**Comment by AntsyLich** [comment]
> This would allow merging language based factory sources into one
Not sure I like this

**Comment by AwkwardPeak7** [comment]
>  Not sure I like this

The idea is to be able to seperate different chapter types/versions. For example volume release or chapter release, some sources provide them on the same page. Or languages, where all languages are there on single page. This can sources which provide 'raw' and translated chapters etc, or multiple different translations like MD, Comick etc. 

Won't be used for things where multiple calls needs to be made to get different languages.
Also won't/shouldn't be used to deduplicate scanlators

**Comment by AntsyLich** [comment]
I can understand the other thing. What I don't like is merging sources like MD and Comick into a singular source and using branch to set languages.

**Comment by AwkwardPeak7** [comment]
We would have to take mogration into account as well, so md already being factory source will continue to do so. This was an example.

Also, I think it is much easier to switch language from branch instead of searching again in a different language same source... But thats just my opinion on factory sources...

**Comment by AntsyLich** [comment]
> searching again in a different language same source

We can probably add something else to facilitate this which in turn will show "See in another language" on the UI.

And that out of the way probably need another name for this.

**Comment by AwkwardPeak7** [comment]
suggest a name.

`listing` ? (volume listing; chapter listing; raw listing etc)
`type` ? (chapter type: volume; chapter; raw)

**Comment by AntsyLich** [comment]
Deciding on not adding this

**Pull request closed without merging**
