### PR TITLE
Add view count & like count to manga

### PR DESCRIPTION
**Pull request by cuong-tran**

### CODE REVIEW

**Comment by AntsyLich** [comment]
This comes with the issue of users asking a way to like from inside the app 🤔. Additionally chapters can also have view and likes

**Comment by cuong-tran** [comment]
> This comes with the issue of users asking a way to like from inside the app 🤔. Additionally chapters can also have view and likes

right, that was what I thought of right after the PR. anw the like/view on manga will lead to a feature in which user can sort their library by that.
- Like from app: go to webview
- Chapter like: who care about that

**Comment by MajorTanya** [comment]
> Like from app: go to webview

Better actually go to a normal browser, since some pages don't play nice with WebView at all.

**Comment by AntsyLich** [comment]
I'm inclined towards a no after giving this a long thought

**Comment by cuong-tran** [comment]
leave it to extension sorting then. Now I also feel like this is useless.

**Pull request closed without merging**
